# site settings
title: Xiao Wang Personal Website
description:
baseurl: "" # the subpath of your site, e.g. /blog

name: Xiao Wang's Personal Site
# build settings
markdown: kramdown
theme: jekyll-theme-leap-day
# site settings
permalink: /blog/:year/:month/:day/:title
#plugins:
#  - jekyll-sitemap
