# site settings
baseurl: "" # the subpath of your site, e.g. /blog

name: Xiao Wang's Personal Site
# build settings
markdown: kramdown
# site settings
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-sitemap
